### PR TITLE
enable https, borrow some stdlib wrapping classes

### PR DESCRIPTION
**Pull request by chrhlnd**
Wanted to have the option of this running with https.

### CODE REVIEW

**Comment by rubyist** [comment]
This looks like a great contribution, thanks! If you agree to the CLA I can merge it in.

**Comment by chrhlnd** [comment]
https://github.com/github/lfs-test-server/blob/master/CONTRIBUTING.md

Doesn't direct me to any CLA.

Shouldn't be a problem just need to know where to look.

**Comment by rubyist** [comment]
Does it allow you to accept it if you click the "Details" link in the build failure notice on this page?

**Comment by chrhlnd** [comment]
Yes looks good now.

**Comment by rubyist** [comment]
Excellent, thanks!

**Pull request merged**
