### PR TITLE
Management console : download from the oid

### PR DESCRIPTION
**Pull request by Yopai**
As spotted in https://github.com/github/lfs-test-server/issues/38, the management console didn't offer the ability to download the file content.
This PR solves that point.

### CODE REVIEW

**Comment by rubyist** [comment]
I think there's a problem here mixing authentication. This will only work if the admin user/pass matches a "user" user/pass. The metastore `Get()` call is checking that. I think we need to bypass that part of authentication for the raw object stuff.

**Comment by Yopai** [comment]
You're right.
(I only had in mind the case when the server is public, as that's how I intent to use it. And it works in this case, too)
Oh, while I'm thinking, too : I just saw embed-go has to be rerun, my commit included swap files.
But time to sleep for me. I'll see all that tomorrow.

**Comment by Yopai** [comment]
I implemented what (I understood you) said :
I override meta_store.Get to bypass authentication by creating a UnsafeGet method (then Get is just : authentication; return UnsafeGet)

**Comment by Yopai** [comment]
There could be another option : we could consider that, in a general way, if we're logged in admin, we don't need a user authentication.
I modified meta_store.authenticate this way. ~~ See attached patch. ~~ Can't attach the patch, I push the commit on the PR.

**Comment by rubyist** [comment]
Sorry I totally missed the extra changes you made. Thanks for the PR, it's now merged in!

**Pull request merged**
